"""empty message

Revision ID: 84484f2d5029
Revises: 
Create Date: 2022-02-10 23:06:04.074200

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84484f2d5029'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=5000), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nick_name', sa.String(length=200), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=11), nullable=True),
    sa.Column('login_date', sa.DateTime(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('t_emp')
    op.drop_table('t_payment')
    op.drop_table('dept')
    op.drop_table('bonus')
    op.drop_table('t_student')
    op.drop_table('student')
    op.drop_table('t_dept')
    op.drop_table('salgrade')
    op.drop_table('teacher_login')
    op.drop_table('j_course')
    op.drop_table('t_class')
    op.drop_table('j_teacher')
    op.drop_table('j_score')
    op.drop_table('emp')
    op.drop_table('student_score')
    op.drop_table('j_student')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('j_student',
    sa.Column('sno', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('sage', mysql.DATETIME(), nullable=False),
    sa.Column('ssex', mysql.CHAR(length=2), nullable=False),
    sa.PrimaryKeyConstraint('sno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student_score',
    sa.Column('sid', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('sdept', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('chinese', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('math', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('english', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('average_score', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('classmate_score', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('teacher_score', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.Column('total_score', mysql.FLOAT(precision=5, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('emp',
    sa.Column('EMPNO', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ENAME', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('JOB', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('MGR', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('HIREDATE', sa.DATE(), nullable=True),
    sa.Column('SAL', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    sa.Column('COMM', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    sa.Column('DEPTNO', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['DEPTNO'], ['dept.DEPTNO'], name='FK_DEPTNO'),
    sa.PrimaryKeyConstraint('EMPNO'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('j_score',
    sa.Column('sno', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cno', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cno'], ['j_course.cno'], name='FK_SCORE_course'),
    sa.ForeignKeyConstraint(['sno'], ['j_student.sno'], name='FK_score_student'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('j_teacher',
    sa.Column('tno', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tname', mysql.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('tno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_class',
    sa.Column('cno', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('cname', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('room', mysql.CHAR(length=4), nullable=True),
    sa.PrimaryKeyConstraint('cno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('j_course',
    sa.Column('cno', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cname', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('tno', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('cno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('teacher_login',
    sa.Column('username', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=10), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('salgrade',
    sa.Column('GRADE', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('LOSAL', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    sa.Column('HISAL', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('GRADE'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_dept',
    sa.Column('dept_no', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('d_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('dept_no'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('student',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('NAME', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('chinese', mysql.FLOAT(), nullable=True),
    sa.Column('english', mysql.FLOAT(), nullable=True),
    sa.Column('math', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_student',
    sa.Column('sno', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('classno', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('sno'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('bonus',
    sa.Column('ENAME', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('JOB', mysql.VARCHAR(length=9), nullable=True),
    sa.Column('SAL', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    sa.Column('COMM', mysql.DOUBLE(precision=7, scale=2, asdecimal=True), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dept',
    sa.Column('DEPTNO', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('DNAME', mysql.VARCHAR(length=14), nullable=True),
    sa.Column('LOC', mysql.VARCHAR(length=13), nullable=True),
    sa.PrimaryKeyConstraint('DEPTNO'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_payment',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False, comment='主键id'),
    sa.Column('login_user', mysql.VARCHAR(length=64), nullable=True, comment='当前登录用户名称'),
    sa.Column('recipient', mysql.VARCHAR(length=64), nullable=True, comment='收件人'),
    sa.Column('province', mysql.VARCHAR(length=64), nullable=True, comment='省'),
    sa.Column('city', mysql.VARCHAR(length=64), nullable=True, comment='市'),
    sa.Column('area', mysql.VARCHAR(length=64), nullable=True, comment='区'),
    sa.Column('address', mysql.VARCHAR(length=100), nullable=True, comment='详细地址'),
    sa.Column('telephone', mysql.VARCHAR(length=64), nullable=True, comment='手机号码'),
    sa.Column('default_address', mysql.INTEGER(), autoincrement=False, nullable=True, comment='默认收货地址 1-是,0-否'),
    sa.Column('enabled', mysql.INTEGER(), autoincrement=False, nullable=True, comment='逻辑删除 1-已删除,0-未删除'),
    sa.Column('gmt_create', mysql.BIGINT(), autoincrement=False, nullable=True, comment='创建时间'),
    sa.Column('gmt_modified', mysql.BIGINT(), autoincrement=False, nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户地址',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_comment='用户地址',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('t_emp',
    sa.Column('emp_no', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('e_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('job', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('hire_date', sa.DATE(), nullable=True),
    sa.Column('sal', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('dept_no', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dept_no'], ['t_dept.dept_no'], name='t_emp_ibfk_1', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('emp_no'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('person')
    # ### end Alembic commands ###
